# Generated by Django 2.1.7 on 2019-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190514_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.CharField(default='10;10', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='lon',
            field=models.CharField(default='10;10', max_length=3),
            preserve_default=False,
        ),
    ]
